services:
  database:
    container_name: rage-dev-database
    image: postgres:17.2
    environment:
      - POSTGRES_PASSWORD=${SERVER_DB_PASSWORD}
      - POSTGRES_USER=${SERVER_DB_USERNAME}
      - POSTGRES_DB=${SERVER_DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - app_network

  server:
    container_name: rage-dev-server
    build:
      context: ../../packages/server
      dockerfile: ../../docker/dev/Dockerfile.server
    environment:
      - DB_HOST=${SERVER_DB_HOST}
      - DB_USERNAME=${SERVER_DB_USERNAME}
      - DB_PASSWORD=${SERVER_DB_PASSWORD}
      - DB_NAME=${SERVER_DB_NAME}
    ports:
      - "22006:22006"
      - "22005:22005/udp"
    volumes:
      - ../../packages/server:/app
    networks:
      - app_network
    depends_on:
      - client

  client:
    container_name: rage-dev-client
    build:
      context: ../../packages/client
      dockerfile: ../../docker/dev/Dockerfile.client
    volumes:
      - ../../packages/client:/app
    ports:
      - "5173:5173"
    networks:
      - app_network
    depends_on:
      - database

volumes:
  pg_data:

networks:
  app_network:
    driver: bridge
