FROM node:20 AS base
WORKDIR /app
COPY package*.json ./

FROM base AS build
WORKDIR /app
RUN npm install
COPY . .
RUN npm run build

FROM base AS final
WORKDIR /app
COPY --from=build /app/dist ./dist
RUN npm install --omit=dev

FROM disinterpreter/ragemp-server
WORKDIR /ragemp/ragemp-srv
COPY --from=final /app .